name: ON-PUSH:Tag release

on:
  push:
    branches:
      - 'development'
  pull_request:

jobs:
  call-smoke-test-workflow:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/composite_smoke_test.yml
    with:
      local_ref: ${{ github.ref_name }}
    secrets: inherit
  
  create-tag:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v1.0.0 # Optional fallback tag to use when no tag can be found
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.v_patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.v_patch }}
          release_name: ${{ steps.createmilestone.title }}
          body: "E2E Composite release for  ${{ steps.semvers.outputs.v_patch }}"
          draft: false
          prerelease: false

  